apiVersion: apps/v1
kind: Deployment

metadata:
  name: nearby-backend

spec:

  # Staging uses fewer replicas
  replicas: 1

  template:

    spec:

      containers:

        - name: nearby-backend

          # Dummy ECR image
          image: 000000000000.dkr.ecr.ap-south-1.amazonaws.com/nearby-backend:staging-latest